---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: registry.devops.eds/playwright:ulduar
  environment:
    server_url: server-app
  commands:
  - pip -r requirements.txt
  - playwright install
  - playwright install-deps
  environment:
    from_secret:
      API_KEY: API_KEY

services:
- name: server-app
  image: registry.devops.eds/python:buster
  commands:
  - pip install -r requirements.txt
  - python app.py
