FROM nginx:1.21.3
COPY proxy/default.conf /etc/nginx/conf.d/default.conf
COPY proxy/ssl/ /etc/ssl/certs/nginx/
COPY proxy/includes/ /etc/nginx/includes/
# COPY proxy/page-not-found.html /var/www/html/page-not-found.html
