---
kind: pipeline
type: docker
name: Icecrown-Pipeline

steps:
- name: docker
  image: registry.devops.eds/docker:1
  commands:
    - docker login https://registry.devops.eds -u $USERNAME -p $PASSWORD
    - docker build -t registry.devops.eds/playwright:ulduar .
    - docker push registry.devops.eds/playwright:ulduar
  environment:
    PASSWORD:
      from_secret: docker_password
    USERNAME:
      from_secret: docker_username